"""
Author : Achintya Gupta
Date Created : 22-09-2020
"""

"""
Problem Statement
------------------------------------------------
Q)  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
from utils import timing_decorator

@timing_decorator
def find_fiboeven():
    thresh = 4_000_000
    nums = [1,2]
    total = 2
    while nums[-1]<thresh:
        next_inseq = nums[-1]+nums[-2]
        nums.append(next_inseq)
        if next_inseq%2==0:
            total += next_inseq

    print('Last calculated number in Fibonacci Sequence : ', nums[-1])
    print('Total : ', total)


find_fiboeven()
